ref(maven): Improve logging for `maven` target
getsentry/craft pull request #275
Opened 2021-08-17 09:51 UTC by iker-barriocanal

- Don't log when not finding BOMs. Most of the packages aren't supposed to be BOM files, and logging this may give the impression that something is missing when it's not.
- On debug log-level, log output of commands.

2021-08-17 11:24 UTC, AbhiPrasad commented on src/targets/maven.ts
> +      if (output.length === 0) {
We can combine this conditional.

2021-08-17 11:24 UTC, AbhiPrasad commented on src/targets/maven.ts
> +        this.logger.debug(`The command didn't have any output.`);
Hard to know what the command is from this statement, would be helpful to have some details about the command

2021-08-17 12:14 UTC, BYK requested changes

2021-08-17 12:14 UTC, BYK commented on src/targets/maven.ts
> +  private logCmdOutput(output: Buffer | undefined): void {
You shouldn't need any of this as `spawnProcess` does it underneath:

https://github.com/getsentry/craft/blob/a015c79de78bbc672570a38cb2177786e2fa93db/src/utils/system.ts#L174-L182

2021-08-17 14:43 UTC, BYK requested changes
I don't understand the motivation behind the `this.logger.level >= LogLevel.Debug` condition.

`spawnProcess` already logs with level `info` if this is `true` at all times. If we want to see the output for debugging purposes, we can always set the logging level to `trace` for that specific session, right?

2021-08-17 14:43 UTC, BYK commented on src/targets/maven.ts
> +      { showStdout: this.logger.level >= LogLevel.Debug }
Why are we doing this?

2021-08-18 13:14 UTC, BYK approved these changes

2021-08-19 09:33 UTC, merged