ref: Pin cocoapods version
getsentry/craft pull request #496
Opened 2023-10-23 12:33 UTC by brustolin

Pinned cocoapods version to avoid surprises!

2023-10-23 13:20 UTC, asottile-sentry commented on Dockerfile
> +COPY package.json yarn.lock Gemfile Gemfile.lock ./
this should not get copied here -- this invalidates every layer when the gemfile changes but it is not used until a much much later layer

2023-10-23 13:40 UTC, philipphofmann approved these changes
If it works, LGTM.

2023-10-23 13:40 UTC, philipphofmann commented on Gemfile
> +gem "cocoapods", "= 1.13.0"
`m`: @brustolin, please add a comment explaining why we need to pin these versions, and why we can't use `gem install cocoapods --no-document -v 1.21.11.

2023-10-23 13:40 UTC, philipphofmann commented on Dockerfile
> +  # temporary workaround for cocoapod crash
`m`: Please add a link to the issue and a short explanation.

2023-10-23 13:42 UTC, asottile-sentry requested changes

2023-10-23 13:42 UTC, asottile-sentry commented on Dockerfile
> +  && gem install cocoapods -v 1.13.0 \
this should have a fully pinned gemfile instead of pinning a handful of things -- this is going to be fragile as written

2023-10-23 14:33 UTC, asottile-sentry commented on Dockerfile
> +  && gem install -g -no-document\
this command is incorrect (see the original command) and the space should be preserved

2023-10-23 14:33 UTC, asottile-sentry commented on Gemfile
> +# activesupport 7.1.1 is broken, and cocoapods dont have a pinned
dont -> doesn't

2023-10-23 14:37 UTC, asottile-sentry commented on .dockerignore
> +!/Gemfile.lock
these were sorted -- can you fix that?

2023-10-23 15:52 UTC, asottile-sentry approved these changes
![](https://i.fluffy.cc/27MHQpGVHf8zsBqx96gxT5PB5mS1jtjD.gif)

2023-10-24 07:00 UTC, philipphofmann reviewed
Thanks @brustolin.

2023-10-24 07:42 UTC, merged