ref: Better logging for github target
getsentry/craft pull request #536
Opened 2024-05-16 11:49 UTC by mydea

I have no idea why the check for latest failed here: https://github.com/getsentry/publish/actions/runs/9111373580/job/25048351278#step:11:2317

So adding some more logging here is not unreasonable I guess!

2024-05-16 11:56 UTC, asottile-sentry commented
can you describe the issue? it's unclear what you're trying to solve for (additionally this PR makes changes beyond logging)

2024-05-16 12:08 UTC, mydea commented
> can you describe the issue? it's unclear what you're trying to solve for (additionally this PR makes changes beyond logging)

The problem is that it does not seem to be working, it is still marking the stuff as latest. But I can't see anything wrong, and the existing logs make it impossible to know where this failed (e.g. could it not find the previous release? is the version from there picked up incorrectly? ...)

2024-05-16 12:09 UTC, Lms24 approved these changes
LGTM!

2024-05-16 12:15 UTC, asottile-sentry commented
probably don't need the logging -- the problem is that the draft was created correctly (non-latest) but then converted to latest when moved out of draft because this defaults to `make_latest: true`: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release

2024-05-16 12:28 UTC, BYK commented
I think the additional logging makes sense but it's better not to change other stuff.

2024-05-16 12:33 UTC, mydea commented
> probably don't need the logging -- the problem is that the draft was created correctly (non-latest) but then converted to latest when moved out of draft because this defaults to `make_latest: true`: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release

Ahh, great catch. I'll update this accordingly! I think I'll leave the logging in, it can still be helpful I'd say? At least the log for what the previous release was!

2024-05-16 12:34 UTC, asottile-sentry commented
> > probably don't need the logging -- the problem is that the draft was created correctly (non-latest) but then converted to latest when moved out of draft because this defaults to `make_latest: true`: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release
> 
> Ahh, great catch. I'll update this accordingly! I think I'll leave the logging in, it can still be helpful I'd say? At least the log for what the previous release was!

🤷 personally I'd rather not just because it's even more output clutter -- and it wouldn't have helped us find the answer here

2024-05-16 12:38 UTC, mydea commented
So I updated this to ensure we set `make_latest` in `publishRelease` as well, which meant that I extracted this out to only call this once!

2024-05-23 12:48 UTC, asottile-sentry commented
as I requested above, and as I've done in many of your PRs: please limit the change to just the functional change instead of coupling it with unrelated (and imo undesirable) changes.  this makes it easier to review, easier to reason about, easier to rollback, and generally is how one should approach development

2025-01-10 09:46 UTC, mydea commented
I updated this to only include minimal changes necessary to make this work. The core change is that we ensure to also set `make_latest` when we call `updateRelease` now. I also included the fix from https://github.com/getsentry/craft/pull/567 as this is moved around here.

2025-01-10 10:12 UTC, BYK requested changes
Requesting changes not because of the code but for the lack of a PR description explaining what was going wrong, what exactly we are fixing etc.

If this is an important change and if it's not too hard, adding a test would also be nice (I'm fine not adding if there are none though)

2025-01-10 10:12 UTC, BYK commented on src/targets/github.ts
> +      make_latest: isLatest ? 'true' : 'false',
Why is this a string?

2025-01-10 10:12 UTC, BYK commented on src/targets/github.ts
> +    isLatest = true
```suggestion
    setAsLatest = true
```

Also, not to derail your patch but boolean function arguments are frowned upon as they make it very hard to see what's going on from the callsite: `createDraftRelease('1.2.3', 'aaaef32', undefined, false)` would be quite hard to make sense of.

You may want to consider converting all of them to an arguments object or just add a final `options` object with `setAsLatest` as its only known key for now?

2025-01-10 10:12 UTC, BYK commented on src/targets/github.ts
> +  public async publishRelease(release: GitHubRelease, isLatest = true) {
Same concern as above re boolean args and also naming. Would prefer something like `setAsLatest` or `makeLatest`

2025-01-10 10:13 UTC, mydea commented on src/targets/github.ts
> +    isLatest = true
happy to do that, I tried to do minimal changes in the PR, but I agree - I'll convert this to an object!

2025-01-10 10:14 UTC, mydea commented on src/targets/github.ts
> +      make_latest: isLatest ? 'true' : 'false',
Here: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release it is documented as type `string`, for whatever reason...

2025-01-10 10:40 UTC, merged